#! /bin/sh

kill `cat data/manager.pid`  2>/dev/null 1>&2

printf "stop_manager ..."
for ticktock in 1 2 3 4 5 6 7 8 9 10
do
  kill -0 `cat data/manager.pid`  2>/dev/null 1>&2
  if [ $? != 0 ]; then
      echo `cat data/manager.pid` is gone $?
      exit 0
  fi
  sleep 1
  printf "."
done
echo  ' force -9'
kill -9 `cat data/manager.pid`  2>/dev/null 1>&2

